//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace booksahre.BookService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BookServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BookService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkBookExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback createBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBookByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTotalPageSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadCoverBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBookCoversOperationCompleted;
        
        private System.Threading.SendOrPostCallback reviewBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTopReviewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BookService() {
            this.Url = global::booksahre.Properties.Settings.Default.booksahre_BookService_BookService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkBookExistCompletedEventHandler checkBookExistCompleted;
        
        /// <remarks/>
        public event createBookCompletedEventHandler createBookCompleted;
        
        /// <remarks/>
        public event getBookByIdCompletedEventHandler getBookByIdCompleted;
        
        /// <remarks/>
        public event searchBookCompletedEventHandler searchBookCompleted;
        
        /// <remarks/>
        public event getTotalPageSearchCompletedEventHandler getTotalPageSearchCompleted;
        
        /// <remarks/>
        public event uploadCoverBookCompletedEventHandler uploadCoverBookCompleted;
        
        /// <remarks/>
        public event getBookCoversCompletedEventHandler getBookCoversCompleted;
        
        /// <remarks/>
        public event reviewBookCompletedEventHandler reviewBookCompleted;
        
        /// <remarks/>
        public event getTopReviewCompletedEventHandler getTopReviewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkBookExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Book checkBookExist(string isbn) {
            object[] results = this.Invoke("checkBookExist", new object[] {
                        isbn});
            return ((Book)(results[0]));
        }
        
        /// <remarks/>
        public void checkBookExistAsync(string isbn) {
            this.checkBookExistAsync(isbn, null);
        }
        
        /// <remarks/>
        public void checkBookExistAsync(string isbn, object userState) {
            if ((this.checkBookExistOperationCompleted == null)) {
                this.checkBookExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckBookExistOperationCompleted);
            }
            this.InvokeAsync("checkBookExist", new object[] {
                        isbn}, this.checkBookExistOperationCompleted, userState);
        }
        
        private void OncheckBookExistOperationCompleted(object arg) {
            if ((this.checkBookExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkBookExistCompleted(this, new checkBookExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int createBook(string ISBN, string title, string author, string tag, string language, string description, int idUser) {
            object[] results = this.Invoke("createBook", new object[] {
                        ISBN,
                        title,
                        author,
                        tag,
                        language,
                        description,
                        idUser});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createBookAsync(string ISBN, string title, string author, string tag, string language, string description, int idUser) {
            this.createBookAsync(ISBN, title, author, tag, language, description, idUser, null);
        }
        
        /// <remarks/>
        public void createBookAsync(string ISBN, string title, string author, string tag, string language, string description, int idUser, object userState) {
            if ((this.createBookOperationCompleted == null)) {
                this.createBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateBookOperationCompleted);
            }
            this.InvokeAsync("createBook", new object[] {
                        ISBN,
                        title,
                        author,
                        tag,
                        language,
                        description,
                        idUser}, this.createBookOperationCompleted, userState);
        }
        
        private void OncreateBookOperationCompleted(object arg) {
            if ((this.createBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createBookCompleted(this, new createBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBookById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Book getBookById(int idBook) {
            object[] results = this.Invoke("getBookById", new object[] {
                        idBook});
            return ((Book)(results[0]));
        }
        
        /// <remarks/>
        public void getBookByIdAsync(int idBook) {
            this.getBookByIdAsync(idBook, null);
        }
        
        /// <remarks/>
        public void getBookByIdAsync(int idBook, object userState) {
            if ((this.getBookByIdOperationCompleted == null)) {
                this.getBookByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBookByIdOperationCompleted);
            }
            this.InvokeAsync("getBookById", new object[] {
                        idBook}, this.getBookByIdOperationCompleted, userState);
        }
        
        private void OngetBookByIdOperationCompleted(object arg) {
            if ((this.getBookByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBookByIdCompleted(this, new getBookByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Book[] searchBook(string query, string filter, int page) {
            object[] results = this.Invoke("searchBook", new object[] {
                        query,
                        filter,
                        page});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void searchBookAsync(string query, string filter, int page) {
            this.searchBookAsync(query, filter, page, null);
        }
        
        /// <remarks/>
        public void searchBookAsync(string query, string filter, int page, object userState) {
            if ((this.searchBookOperationCompleted == null)) {
                this.searchBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchBookOperationCompleted);
            }
            this.InvokeAsync("searchBook", new object[] {
                        query,
                        filter,
                        page}, this.searchBookOperationCompleted, userState);
        }
        
        private void OnsearchBookOperationCompleted(object arg) {
            if ((this.searchBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchBookCompleted(this, new searchBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTotalPageSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getTotalPageSearch(string filter, string query) {
            object[] results = this.Invoke("getTotalPageSearch", new object[] {
                        filter,
                        query});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getTotalPageSearchAsync(string filter, string query) {
            this.getTotalPageSearchAsync(filter, query, null);
        }
        
        /// <remarks/>
        public void getTotalPageSearchAsync(string filter, string query, object userState) {
            if ((this.getTotalPageSearchOperationCompleted == null)) {
                this.getTotalPageSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTotalPageSearchOperationCompleted);
            }
            this.InvokeAsync("getTotalPageSearch", new object[] {
                        filter,
                        query}, this.getTotalPageSearchOperationCompleted, userState);
        }
        
        private void OngetTotalPageSearchOperationCompleted(object arg) {
            if ((this.getTotalPageSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTotalPageSearchCompleted(this, new getTotalPageSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uploadCoverBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void uploadCoverBook(string rootPath, string[] fileName, byte[][] bytes, int idBook) {
            this.Invoke("uploadCoverBook", new object[] {
                        rootPath,
                        fileName,
                        bytes,
                        idBook});
        }
        
        /// <remarks/>
        public void uploadCoverBookAsync(string rootPath, string[] fileName, byte[][] bytes, int idBook) {
            this.uploadCoverBookAsync(rootPath, fileName, bytes, idBook, null);
        }
        
        /// <remarks/>
        public void uploadCoverBookAsync(string rootPath, string[] fileName, byte[][] bytes, int idBook, object userState) {
            if ((this.uploadCoverBookOperationCompleted == null)) {
                this.uploadCoverBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadCoverBookOperationCompleted);
            }
            this.InvokeAsync("uploadCoverBook", new object[] {
                        rootPath,
                        fileName,
                        bytes,
                        idBook}, this.uploadCoverBookOperationCompleted, userState);
        }
        
        private void OnuploadCoverBookOperationCompleted(object arg) {
            if ((this.uploadCoverBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadCoverBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBookCovers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getBookCovers(int idBook) {
            object[] results = this.Invoke("getBookCovers", new object[] {
                        idBook});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getBookCoversAsync(int idBook) {
            this.getBookCoversAsync(idBook, null);
        }
        
        /// <remarks/>
        public void getBookCoversAsync(int idBook, object userState) {
            if ((this.getBookCoversOperationCompleted == null)) {
                this.getBookCoversOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBookCoversOperationCompleted);
            }
            this.InvokeAsync("getBookCovers", new object[] {
                        idBook}, this.getBookCoversOperationCompleted, userState);
        }
        
        private void OngetBookCoversOperationCompleted(object arg) {
            if ((this.getBookCoversCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBookCoversCompleted(this, new getBookCoversCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/reviewBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reviewBook(int idBook, int idUser, string content) {
            this.Invoke("reviewBook", new object[] {
                        idBook,
                        idUser,
                        content});
        }
        
        /// <remarks/>
        public void reviewBookAsync(int idBook, int idUser, string content) {
            this.reviewBookAsync(idBook, idUser, content, null);
        }
        
        /// <remarks/>
        public void reviewBookAsync(int idBook, int idUser, string content, object userState) {
            if ((this.reviewBookOperationCompleted == null)) {
                this.reviewBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreviewBookOperationCompleted);
            }
            this.InvokeAsync("reviewBook", new object[] {
                        idBook,
                        idUser,
                        content}, this.reviewBookOperationCompleted, userState);
        }
        
        private void OnreviewBookOperationCompleted(object arg) {
            if ((this.reviewBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reviewBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTopReview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Review[] getTopReview(int top, int idBook) {
            object[] results = this.Invoke("getTopReview", new object[] {
                        top,
                        idBook});
            return ((Review[])(results[0]));
        }
        
        /// <remarks/>
        public void getTopReviewAsync(int top, int idBook) {
            this.getTopReviewAsync(top, idBook, null);
        }
        
        /// <remarks/>
        public void getTopReviewAsync(int top, int idBook, object userState) {
            if ((this.getTopReviewOperationCompleted == null)) {
                this.getTopReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTopReviewOperationCompleted);
            }
            this.InvokeAsync("getTopReview", new object[] {
                        top,
                        idBook}, this.getTopReviewOperationCompleted, userState);
        }
        
        private void OngetTopReviewOperationCompleted(object arg) {
            if ((this.getTopReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTopReviewCompleted(this, new getTopReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Book {
        
        private int idField;
        
        private int idUserField;
        
        private string titleField;
        
        private string authorField;
        
        private string iSBNField;
        
        private string languageField;
        
        private string descriptionField;
        
        private string tagField;
        
        private bool statusField;
        
        private string getImageField;
        
        private string[] getImagesField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string getImage {
            get {
                return this.getImageField;
            }
            set {
                this.getImageField = value;
            }
        }
        
        /// <remarks/>
        public string[] getImages {
            get {
                return this.getImagesField;
            }
            set {
                this.getImagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Review {
        
        private int idField;
        
        private int idBookField;
        
        private int idUserField;
        
        private string contentField;
        
        private System.DateTime createDateField;
        
        private string usernameField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int idBook {
            get {
                return this.idBookField;
            }
            set {
                this.idBookField = value;
            }
        }
        
        /// <remarks/>
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void checkBookExistCompletedEventHandler(object sender, checkBookExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkBookExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkBookExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void createBookCompletedEventHandler(object sender, createBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getBookByIdCompletedEventHandler(object sender, getBookByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBookByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBookByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void searchBookCompletedEventHandler(object sender, searchBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getTotalPageSearchCompletedEventHandler(object sender, getTotalPageSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTotalPageSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTotalPageSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void uploadCoverBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getBookCoversCompletedEventHandler(object sender, getBookCoversCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBookCoversCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBookCoversCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void reviewBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getTopReviewCompletedEventHandler(object sender, getTopReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTopReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTopReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Review[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Review[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591